# Generated by Django 5.2.4 on 2025-07-16 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoRecomendado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('area', models.CharField(max_length=255, verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Curso recomendado',
                'verbose_name_plural': 'Cursos recomendados',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('habilidades', models.TextField(blank=True, null=True, verbose_name='Habilidades')),
                ('experiencia', models.TextField(blank=True, null=True, verbose_name='Experiência')),
                ('educacao', models.TextField(blank=True, null=True, verbose_name='Educação')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Currículo',
                'verbose_name_plural': 'Currículos',
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='Requisitos')),
                ('link_aplicacao', models.URLField(blank=True, null=True, verbose_name='Link para candidatura')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('localidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidade')),
                ('modalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade')),
                ('tipo_contrato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Contrato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
    ]
