# Generated by Django 5.2.4 on 2025-07-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='experiencia',
            field=models.CharField(choices=[('Junior', 'Júnior'), ('Pleno', 'Pleno'), ('Senior', 'Sênior')], default='Junior', max_length=10, verbose_name='Experiência'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='modalidade',
            field=models.CharField(choices=[('Hibrido', 'Híbrido'), ('Home Office', 'Home Office'), ('Presencial', 'Presencial')], max_length=20, verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='vaga',
            name='tipo_contrato',
            field=models.CharField(choices=[('CLT', 'CLT'), ('Pessoa Juridica', 'Pessoa Jurídica')], max_length=20, verbose_name='Tipo de Contrato'),
        ),
    ]
